# Generated by Django 5.1.6 on 2025-02-23 00:51

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SkinCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserIngredientExclusions',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fragrance', api.models.DefaultFalseBooleanField(default=False)),
                ('alcohol', api.models.DefaultFalseBooleanField(default=False)),
                ('paraben_and_sulfate', api.models.DefaultFalseBooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProductConcerns',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cruelty_free', api.models.DefaultFalseBooleanField(default=False)),
                ('vegan', api.models.DefaultFalseBooleanField(default=False)),
                ('eco_friendly_packaging', api.models.DefaultFalseBooleanField(default=False)),
                ('sustainable_sourcing', api.models.DefaultFalseBooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkinConcerns',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('acne', api.models.DefaultFalseBooleanField(default=False)),
                ('large_pores', api.models.DefaultFalseBooleanField(default=False)),
                ('loss_of_firmness', api.models.DefaultFalseBooleanField(default=False)),
                ('dark_circles', api.models.DefaultFalseBooleanField(default=False)),
                ('hyper_pigmentation', api.models.DefaultFalseBooleanField(default=False)),
                ('congested_skin', api.models.DefaultFalseBooleanField(default=False)),
                ('sun_damange', api.models.DefaultFalseBooleanField(default=False)),
                ('puffy_eyes', api.models.DefaultFalseBooleanField(default=False)),
                ('dehydrated', api.models.DefaultFalseBooleanField(default=False)),
                ('redness', api.models.DefaultFalseBooleanField(default=False)),
                ('scarring', api.models.DefaultFalseBooleanField(default=False)),
                ('aging', api.models.DefaultFalseBooleanField(default=False)),
                ('textured', api.models.DefaultFalseBooleanField(default=False)),
                ('wrinkles', api.models.DefaultFalseBooleanField(default=False)),
                ('sensitive', api.models.DefaultFalseBooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day', models.CharField(choices=[('day', 'Day'), ('night', 'Night')], max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.routine')),
            ],
        ),
        migrations.AddField(
            model_name='routine',
            name='products',
            field=models.ManyToManyField(through='api.RoutineProduct', to='api.product'),
        ),
        migrations.CreateModel(
            name='UserAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.allergy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='allergy',
            name='user_id',
            field=models.ManyToManyField(through='api.UserAllergy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserSkinCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skincondition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='skincondition',
            name='user_id',
            field=models.ManyToManyField(through='api.UserSkinCondition', to=settings.AUTH_USER_MODEL),
        ),
    ]
