# Generated by Django 5.1.6 on 2025-03-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineproduct',
            name='instructions',
            field=models.CharField(default='N/A', max_length=400),
        ),
    ]
